---
#usage: ansible-playbook pb -k -K
- name: playbook to rhel
  become: yes
  hosts: all

  tasks:
   - name: ssh key-based authorized login
     authorized_key: user=root
                     exclusive=no
                     key="{{lookup('file', '~/.ssh/id_rsa.pub')}}"

